language: java
jdk:
  # junit5 requires java 8
  - oraclejdk8

before_install:
 - chmod +x gr
install: true

script:
  - ./gr -i build CodeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/
