language: java
jdk:
  - openjdk6
  - oraclejdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_install:
 - chmod +x gradlew
install: true

script:
  - ./gradlew -i build

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.gradle/wrapper/
