language: java
jdk:
  # junit5 requires java 8
  - oraclejdk8
  - oraclejdk9

before_install:
 - chmod +x gr
install: true

script:
  - ./gr -i build CodeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/
